/**
 * VECTORA Animation Engine — Keyframe Generator
 * Produces pure CSS @keyframes definitions for the full 25-technique animation arsenal.
 */

export interface KeyframeGeneratorOptions {
  baseDuration: number;
  easing: string;
  loopIteration: string;
  effectiveDirection: string;
  width: number;
  height: number;
}

export function generateAllKeyframeRules(options: KeyframeGeneratorOptions): string[] {
  const { baseDuration, easing, loopIteration, effectiveDirection, width, height } = options;
  const maxDim = Math.max(width, height, 1000);
  const maxR = Math.sqrt(width * width + height * height) / 2;

  return [
    `/* ========================================================== */`,
    `/* CATEGORY A: REVEAL & DRAW ANIMATIONS                       */`,
    `/* ========================================================== */`,
    `/* 1. Pen Draw-On */`,
    `@keyframes vec-kf-pen-draw-on {`,
    `  0% { stroke-dashoffset: 1; opacity: 0.2; }`,
    `  60% { stroke-dashoffset: 0; opacity: 1; }`,
    `  100% { stroke-dashoffset: 0; opacity: 1; }`,
    `}`,
    `.vec-anim-pen-draw-on path, .vec-anim-pen-draw-on line, .vec-anim-pen-draw-on polyline {`,
    `  stroke-dasharray: 1 !important;`,
    `  pathLength: 1 !important;`,
    `  animation: vec-kf-pen-draw-on ${baseDuration}s ${easing} ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    ``,
    `/* 2. Typewriter Glyphs */`,
    `@keyframes vec-kf-typewriter-glyph {`,
    `  0% { opacity: 0; transform: translateY(4px); }`,
    `  10% { opacity: 1; transform: translateY(0); }`,
    `  100% { opacity: 1; transform: translateY(0); }`,
    `}`,
    `.vec-anim-typewriter text, .vec-anim-typewriter tspan {`,
    `  animation: vec-kf-typewriter-glyph ${baseDuration}s steps(1, end) ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    ``,
    `/* 3. Wipe Reveal */`,
    `@keyframes vec-kf-wipe-reveal {`,
    `  0% { transform: translateX(0); }`,
    `  50% { transform: translateX(${width}px); }`,
    `  100% { transform: translateX(${width}px); }`,
    `}`,
    `.vec-anim-wipe-rect {`,
    `  animation: vec-kf-wipe-reveal ${baseDuration}s ${easing} ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    ``,
    `/* 4. Signature Bleed */`,
    `@keyframes vec-kf-sig-draw {`,
    `  0% { stroke-dashoffset: 1; }`,
    `  50% { stroke-dashoffset: 0; }`,
    `  100% { stroke-dashoffset: 0; }`,
    `}`,
    `@keyframes vec-kf-sig-bleed {`,
    `  0%, 40% { filter: drop-shadow(0 0 0px rgba(0,255,0,0)); }`,
    `  65% { filter: drop-shadow(0 0 6px rgba(0,255,0,0.8)); }`,
    `  100% { filter: drop-shadow(0 0 2px rgba(0,255,0,0.4)); }`,
    `}`,
    `.vec-anim-signature-bleed {`,
    `  animation: vec-kf-sig-bleed ${baseDuration}s ${easing} ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    `.vec-anim-signature-bleed path {`,
    `  stroke-dasharray: 1 !important;`,
    `  pathLength: 1 !important;`,
    `  animation: vec-kf-sig-draw ${baseDuration}s ${easing} ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    ``,
    `/* 5. Iris Aperture Reveal */`,
    `@keyframes vec-kf-iris-expand {`,
    `  0% { r: 0px; }`,
    `  60% { r: ${maxR.toFixed(0)}px; }`,
    `  100% { r: ${maxR.toFixed(0)}px; }`,
    `}`,
    `.vec-anim-iris-circle {`,
    `  animation: vec-kf-iris-expand ${baseDuration}s ${easing} ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    ``,
    `/* ========================================================== */`,
    `/* CATEGORY B: MORPH & TRANSFORM ANIMATIONS                   */`,
    `/* ========================================================== */`,
    `/* 6. Path Morphing */`,
    `@keyframes vec-kf-path-morph {`,
    `  0%, 100% { transform: scale(1) rotate(0deg); }`,
    `  33% { transform: scale(1.06, 0.94) rotate(1.5deg); }`,
    `  66% { transform: scale(0.95, 1.05) rotate(-1.5deg); }`,
    `}`,
    `.vec-anim-path-morph {`,
    `  animation: vec-kf-path-morph ${baseDuration}s ${easing} ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    ``,
    `/* 7. Skeleton Rig Puppet Armature */`,
    `@keyframes vec-kf-joint-swivel {`,
    `  0%, 100% { transform: rotate(-5deg); }`,
    `  50% { transform: rotate(5deg); }`,
    `}`,
    `.vec-anim-skeleton-rig > g {`,
    `  transform-origin: center bottom !important;`,
    `  animation: vec-kf-joint-swivel ${baseDuration}s ease-in-out ${loopIteration} alternate !important;`,
    `}`,
    ``,
    `/* 8. Path Warp / Displacement */`,
    `@keyframes vec-kf-path-warp {`,
    `  0%, 100% { transform: translate(0, 0) skewX(0deg); }`,
    `  25% { transform: translate(-3px, 2px) skewX(1deg); }`,
    `  75% { transform: translate(3px, -2px) skewX(-1deg); }`,
    `}`,
    `.vec-anim-path-warp {`,
    `  filter: url(#vec-anim-def-path-warp);`,
    `  animation: vec-kf-path-warp ${baseDuration}s ease-in-out ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    ``,
    `/* 9. Elastic Bounce Overshoot */`,
    `@keyframes vec-kf-elastic-bounce {`,
    `  0% { transform: scale(0.3); opacity: 0; }`,
    `  50% { transform: scale(1.08); opacity: 1; }`,
    `  70% { transform: scale(0.96); }`,
    `  85% { transform: scale(1.02); }`,
    `  100% { transform: scale(1); opacity: 1; }`,
    `}`,
    `.vec-anim-elastic-bounce {`,
    `  animation: vec-kf-elastic-bounce ${baseDuration}s cubic-bezier(0.68, -0.55, 0.265, 1.55) ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    ``,
    `/* ========================================================== */`,
    `/* CATEGORY C: PARTICLE & EMISSION EFFECTS                    */`,
    `/* ========================================================== */`,
    `/* 10. Particle Trail */`,
    `@keyframes vec-kf-particle-trail {`,
    `  0% { transform: translate(0, 0) scale(1); opacity: 1; }`,
    `  50% { transform: translate(12px, -8px) scale(0.9); opacity: 0.6; }`,
    `  100% { transform: translate(24px, -16px) scale(0.7); opacity: 0; }`,
    `}`,
    `.vec-anim-particle-trail {`,
    `  animation: vec-kf-particle-trail ${baseDuration}s ease-out ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    ``,
    `/* 11. Constellation Draw */`,
    `@keyframes vec-kf-constellation-node {`,
    `  0% { transform: scale(0); opacity: 0; }`,
    `  40% { transform: scale(1.3); opacity: 1; filter: drop-shadow(0 0 8px #00FF00); }`,
    `  60%, 100% { transform: scale(1); opacity: 0.9; }`,
    `}`,
    `.vec-anim-constellation-draw circle {`,
    `  animation: vec-kf-constellation-node ${baseDuration}s ease-out ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    `.vec-anim-constellation-draw line, .vec-anim-constellation-draw path {`,
    `  stroke-dasharray: 400 !important;`,
    `  animation: vec-kf-pen-draw-on ${baseDuration * 1.2}s ease-in-out ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    ``,
    `/* 12. Firefly Particles */`,
    `@keyframes vec-kf-firefly-drift {`,
    `  0%, 100% { transform: translate(0px, 0px) scale(0.8); opacity: 0.3; }`,
    `  25% { transform: translate(15px, -12px) scale(1.2); opacity: 1; filter: drop-shadow(0 0 10px rgba(0,255,255,0.9)); }`,
    `  50% { transform: translate(-10px, -24px) scale(0.9); opacity: 0.5; }`,
    `  75% { transform: translate(-18px, -10px) scale(1.1); opacity: 0.9; filter: drop-shadow(0 0 12px rgba(0,255,100,0.9)); }`,
    `}`,
    `.vec-anim-firefly-particles {`,
    `  animation: vec-kf-firefly-drift ${baseDuration * 1.3}s ease-in-out ${loopIteration} alternate !important;`,
    `}`,
    ``,
    `/* ========================================================== */`,
    `/* CATEGORY D: COLOR & GRADIENT ANIMATIONS                    */`,
    `/* ========================================================== */`,
    `/* 13. Liquid Gradient Flow */`,
    `@keyframes vec-kf-gradient-shift {`,
    `  0% { filter: hue-rotate(0deg) saturate(1); }`,
    `  50% { filter: hue-rotate(180deg) saturate(1.6); }`,
    `  100% { filter: hue-rotate(360deg) saturate(1); }`,
    `}`,
    `.vec-anim-gradient-flow {`,
    `  animation: vec-kf-gradient-shift ${baseDuration * 1.4}s linear ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    ``,
    `/* 14. Hue Rotation */`,
    `@keyframes vec-kf-hue-rotation {`,
    `  0% { filter: hue-rotate(0deg); }`,
    `  100% { filter: hue-rotate(360deg); }`,
    `}`,
    `.vec-anim-hue-rotation {`,
    `  animation: vec-kf-hue-rotation ${baseDuration}s linear ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    ``,
    `/* 15. Chromatic Aberration RGB Split */`,
    `@keyframes vec-kf-chromatic-split {`,
    `  0%, 100% { transform: translate(0, 0); filter: drop-shadow(-2px 0 0 rgba(255,0,0,0.8)) drop-shadow(2px 0 0 rgba(0,255,255,0.8)); }`,
    `  50% { transform: translate(-1px, 1px); filter: drop-shadow(3px -1px 0 rgba(255,0,0,0.8)) drop-shadow(-3px 1px 0 rgba(0,255,255,0.8)); }`,
    `}`,
    `.vec-anim-chromatic-aberration {`,
    `  animation: vec-kf-chromatic-split ${baseDuration * 0.5}s ease-in-out ${loopIteration} alternate !important;`,
    `}`,
    ``,
    `/* ========================================================== */`,
    `/* CATEGORY E: KINETIC & PHYSICS-BASED                        */`,
    `/* ========================================================== */`,
    `/* 16. Wave Distortion */`,
    `@keyframes vec-kf-wave-distortion {`,
    `  0%, 100% { transform: scaleY(1) skewX(0deg); }`,
    `  25% { transform: scaleY(1.04) skewX(2deg); }`,
    `  75% { transform: scaleY(0.96) skewX(-2deg); }`,
    `}`,
    `.vec-anim-wave-distortion {`,
    `  animation: vec-kf-wave-distortion ${baseDuration}s ease-in-out ${loopIteration} alternate !important;`,
    `}`,
    ``,
    `/* 17. Pendulum Swing */`,
    `@keyframes vec-kf-pendulum-swing {`,
    `  0% { transform: rotate(-22deg); }`,
    `  50% { transform: rotate(22deg); }`,
    `  100% { transform: rotate(-22deg); }`,
    `}`,
    `.vec-anim-pendulum-swing {`,
    `  transform-origin: center top !important;`,
    `  animation: vec-kf-pendulum-swing ${baseDuration}s cubic-bezier(0.4, 0, 0.2, 1) ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    ``,
    `/* 18. Domino Cascade */`,
    `@keyframes vec-kf-domino-item {`,
    `  0% { transform: translateY(30px) rotate(-8deg); opacity: 0; }`,
    `  50% { transform: translateY(-4px) rotate(2deg); opacity: 1; }`,
    `  100% { transform: translateY(0) rotate(0deg); opacity: 1; }`,
    `}`,
    `.vec-anim-domino-cascade > g, .vec-anim-domino-cascade > path {`,
    `  animation: vec-kf-domino-item ${baseDuration}s cubic-bezier(0.34, 1.56, 0.64, 1) ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    `.vec-anim-domino-cascade > *:nth-child(1) { animation-delay: 0.05s !important; }`,
    `.vec-anim-domino-cascade > *:nth-child(2) { animation-delay: 0.15s !important; }`,
    `.vec-anim-domino-cascade > *:nth-child(3) { animation-delay: 0.25s !important; }`,
    `.vec-anim-domino-cascade > *:nth-child(4) { animation-delay: 0.35s !important; }`,
    `.vec-anim-domino-cascade > *:nth-child(5) { animation-delay: 0.45s !important; }`,
    `.vec-anim-domino-cascade > *:nth-child(6) { animation-delay: 0.55s !important; }`,
    `.vec-anim-domino-cascade > *:nth-child(7) { animation-delay: 0.65s !important; }`,
    `.vec-anim-domino-cascade > *:nth-child(8) { animation-delay: 0.75s !important; }`,
    ``,
    `/* ========================================================== */`,
    `/* CATEGORY F: ADVANCED CINEMATIC                             */`,
    `/* ========================================================== */`,
    `/* 19. Parallax Depth Scrolling */`,
    `@keyframes vec-kf-parallax-deep {`,
    `  0%, 100% { transform: translate(0, 0); }`,
    `  50% { transform: translate(-10px, -6px); }`,
    `}`,
    `@keyframes vec-kf-parallax-mid {`,
    `  0%, 100% { transform: translate(0, 0); }`,
    `  50% { transform: translate(-20px, -12px); }`,
    `}`,
    `@keyframes vec-kf-parallax-fore {`,
    `  0%, 100% { transform: translate(0, 0); }`,
    `  50% { transform: translate(-35px, -20px); }`,
    `}`,
    `.vec-anim-parallax-depth > *:nth-child(1) { animation: vec-kf-parallax-deep ${baseDuration * 2}s ease-in-out infinite alternate !important; }`,
    `.vec-anim-parallax-depth > *:nth-child(2) { animation: vec-kf-parallax-mid ${baseDuration * 1.5}s ease-in-out infinite alternate !important; }`,
    `.vec-anim-parallax-depth > *:nth-child(3) { animation: vec-kf-parallax-fore ${baseDuration}s ease-in-out infinite alternate !important; }`,
    ``,
    `/* 20. Camera Dolly Zoom */`,
    `@keyframes vec-kf-camera-dolly {`,
    `  0%, 100% { transform: scale(1) translate(0, 0); }`,
    `  50% { transform: scale(1.15) translate(-20px, -15px); }`,
    `}`,
    `.vec-anim-camera-dolly {`,
    `  animation: vec-kf-camera-dolly ${baseDuration * 1.8}s ease-in-out ${loopIteration} alternate !important;`,
    `}`,
    ``,
    `/* 21. Lightning Strike */`,
    `@keyframes vec-kf-lightning-flash {`,
    `  0%, 92%, 96%, 100% { opacity: 1; filter: none; }`,
    `  93% { opacity: 0.1; }`,
    `  94% { opacity: 1; filter: drop-shadow(0 0 30px #FFFFFF) drop-shadow(0 0 50px #00FFFF); }`,
    `  95% { opacity: 0.3; }`,
    `}`,
    `.vec-anim-lightning-strike {`,
    `  animation: vec-kf-lightning-flash ${baseDuration * 0.7}s linear ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
    ``,
    `/* 22. Assembling Puzzle Reveal */`,
    `@keyframes vec-kf-puzzle-piece-1 { 0% { transform: translate(-80px, -60px) rotate(-15deg); opacity: 0; } 100% { transform: translate(0,0) rotate(0); opacity: 1; } }`,
    `@keyframes vec-kf-puzzle-piece-2 { 0% { transform: translate(90px, -70px) rotate(20deg); opacity: 0; } 100% { transform: translate(0,0) rotate(0); opacity: 1; } }`,
    `@keyframes vec-kf-puzzle-piece-3 { 0% { transform: translate(-70px, 90px) rotate(12deg); opacity: 0; } 100% { transform: translate(0,0) rotate(0); opacity: 1; } }`,
    `@keyframes vec-kf-puzzle-piece-4 { 0% { transform: translate(80px, 80px) rotate(-18deg); opacity: 0; } 100% { transform: translate(0,0) rotate(0); opacity: 1; } }`,
    `.vec-anim-assembling-puzzle > *:nth-child(1) { animation: vec-kf-puzzle-piece-1 ${baseDuration}s cubic-bezier(0.16, 1, 0.3, 1) ${loopIteration} ${effectiveDirection} !important; }`,
    `.vec-anim-assembling-puzzle > *:nth-child(2) { animation: vec-kf-puzzle-piece-2 ${baseDuration}s cubic-bezier(0.16, 1, 0.3, 1) ${loopIteration} ${effectiveDirection} !important; }`,
    `.vec-anim-assembling-puzzle > *:nth-child(3) { animation: vec-kf-puzzle-piece-3 ${baseDuration}s cubic-bezier(0.16, 1, 0.3, 1) ${loopIteration} ${effectiveDirection} !important; }`,
    `.vec-anim-assembling-puzzle > *:nth-child(4) { animation: vec-kf-puzzle-piece-4 ${baseDuration}s cubic-bezier(0.16, 1, 0.3, 1) ${loopIteration} ${effectiveDirection} !important; }`,
    ``,
    `/* 23. Liquid Fill */`,
    `@keyframes vec-kf-liquid-rise {`,
    `  0% { transform: translateY(0); }`,
    `  100% { transform: translateY(-${height}px); }`,
    `}`,
    `.vec-anim-liquid-rect {`,
    `  animation: vec-kf-liquid-rise ${baseDuration * 1.5}s ease-in-out ${loopIteration} ${effectiveDirection} !important;`,
    `}`,
  ];
}
